---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prom-tg
spec:
  rules:
  - host: prom-tg.default.uk8s.example.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: prom-tg
            port:
              number: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prom-tg
  labels:
    app: telegraf
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: telegraf
