---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sysdig-account
  labels:
    app: sysdig-example
    role: security
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sysdig-cluster-role
  labels:
    app: sysdig-example
    role: security
rules:
- apiGroups: ["extensions",""]
  resources: ["nodes","namespaces","pods","replicationcontrollers","replicasets","services","daemonsets","deployments","events","configmaps"]
  verbs: ["get","list","watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets","deployments","replicasets","statefulsets"]
  verbs: ["get","list","watch"]
- nonResourceURLs: ["/healthz", "/healthz/*"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sysdig-cluster-role-binding
  labels:
    app: sysdig-example
    role: security
subjects:
- kind: ServiceAccount
  name: sysdig-account
roleRef:
  kind: ClusterRole
  name: sysdig-cluster-role
  apiGroup: rbac.authorization.k8s.io
