---
namespace: default
resources:
- agent.yaml
- event-generator.yaml
- rbac.yaml
configMapGenerator:
- name: falco-config
  files:
  - config/falco.yaml
  - config/falco_rules.local.yaml
  - config/falco_rules.yaml
  - config/k8s_audit_rules.yaml
