---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: weave-scope-app
  namespace: weave
spec:
  rules:
  - host: weave-scope.default.uk8s.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: weave-scope-app
          servicePort: 80
