# from https://github.com/linki/chaoskube/tree/master/examples
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaoskube
  labels:
    app: chaoskube
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chaoskube
  template:
    metadata:
      labels:
        app: chaoskube
    spec:
      serviceAccountName: chaoskube
      containers:
      - name: chaoskube
        image: quay.io/linki/chaoskube:v0.19.0
        args:
        # kill a pod every 10 minutes
        - --interval=10m
        # only target pods in the test environment
        #- --labels=environment=test
        # only consider pods with this annotation
        #- --annotations=chaos.alpha.kubernetes.io/enabled=true
        # exclude all pods in the kube-system, ingress namespaces
        - --namespaces=!kube-system,!ingress
        # don't kill anything on weekends
        - --excluded-weekdays=Sat,Sun
        # don't kill anything during the night or at lunchtime
        - --excluded-times-of-day=22:00-08:00,11:00-13:00
        # don't kill anything as a joke or on christmas eve
        #- --excluded-days-of-year=Apr1,Dec24
        # let's make sure we all agree on what the above times mean
        - --timezone=UTC
        #- --timezone=Asia/Tokyo
        # exclude all pods that haven't been running for at least one hour
        #- --minimum-age=1h
        # terminate pods for real: this disables dry-run mode which is on by default
        - --no-dry-run
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaoskube
  labels:
    app: chaoskube
