---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cloudprober
spec:
  rules:
  - host: cloudprober.default.uk8s.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cloudprober
          servicePort: 9313
  - host: prom-cb.default.uk8s.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: prom-cb
          servicePort: 9090
