---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: powerfulseal
spec:
  rules:
  - host: powerfulseal.default.uk8s.example.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: powerfulseal
            port:
              number: 8080
  - host: powerfulseal-exp.default.uk8s.example.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: powerfulseal-exp
            port:
              number: 9999
